### ISSUE TITLE
implementation of a temperature control system for the cooling fan

### ISSUE THREAD

**Issue by LeilaPiri** [panda-official/TimeSwipe#9]
for this purpose use the integrated temperature sensor of the SAM.

**Comment by i5abell** [comment]
The ventilator control is routed on pin PA09 (34) of the SAM. 
The actual ventilator: https://www.reichelt.de/axial-luefter-30x30x6mm-5v-6-2m-h-15-7dba-sun-mf30060v2-1-p260654.html 

Has to be written in a modular way as separate function, so that it can be used as a code block elsewhere.

**Comment by LeilaPiri** [comment]
- should be implemented using pulse width modulation (PWM), frequency: 1-9 kHz
- 4 steps: 0%, 33%, 66%, 100%

**Comment by IngoKaiser** [comment]
@begodev please give me short feedback about current state on that.

**Comment by begodev** [comment]
> @begodev please give me short feedback about current state on that.

At the moment a temperature sensor class is implemented for the SAM (Branch Issue 9).
But it seems temperature readout is not really precise - it has markable dispersion.
As I remember +- several degrees.

**Comment by IngoKaiser** [comment]
Do you think that's an software issue or precision of temperature sensor?

**Comment by begodev** [comment]
> Do you think that's an software issue or precision of temperature sensor?

I think it is because the way it is calculated: it is actually a ratio of 2 measured points. They have to be measured very precisely via SAM's ADC...
I'm trying to find some precision specs in the manual, but it is only written "The accuracy is dependent on the current temperature, and degrades towards extreme conditions."
But no any certain numbers...

I remembered I get +- several degrees, ther was also some initial firmware at XPlained board with temperature measurements it gave near the same, I can recheck.

**Comment by IngoKaiser** [comment]
since we just wanna use it for fan control. some degrees won't make a difference. 
So since temp class is implemented just fan controller according @LeilaPiri requirements would need to be implemented right?

**Comment by begodev** [comment]
> since we just wanna use it for fan control. some degrees won't make a difference.
> So since temp class is implemented just fan controller according @LeilaPiri requirements would need to be implemented right?

Yes exactly, fan controller with PWM output
